import os
import sys
import glob
from pathlib import Path
from typing import List
from dotenv import load_dotenv

backend_dir = Path(__file__).resolve().parent.parent.parent
if str(backend_dir) not in sys.path:
    sys.path.insert(0, str(backend_dir))

from langchain_core.documents import Document
from app.rag.splitter import TextChunker
from app.rag.embedding import EmbeddingModel
from app.rag.vectorstore import VectorStore
from app.rag.retriever import Retriever

load_dotenv(backend_dir / ".env")

def load_knowledge_base_documents(data_dir: Path) -> List[Document]:
    """Load all text files and master markdown from data directory."""
    documents = []
    
    txt_files = sorted(list(data_dir.glob("*.txt")) + list(data_dir.glob("*.md")))
    print(f"Found {len(txt_files)} knowledge base files in {data_dir}")
    
    for fpath in txt_files:
        if fpath.name == "text file.txt":
            continue # Skip raw uncurated scrape dump
        try:
            content = fpath.read_text(encoding="utf-8", errors="ignore").strip()
            if not content:
                continue
                
            doc = Document(
                page_content=content,
                metadata={
                    "document_id": f"knowledge_base/{fpath.name}",
                    "filename": fpath.name,
                    "owner_id": "default",
                    "is_knowledge_base": True,
                    "page": 1,
                    "source": str(fpath.name)
                }
            )
            documents.append(doc)
            print(f"Loaded: {fpath.name} ({len(content):,} chars)")
        except Exception as e:
            print(f"Error loading {fpath.name}: {e}")
            
    return documents

def ingest_into_store(documents: List[Document], persist_path: str, use_local: bool):
    """Chunk and embed documents into a specific ChromaDB vector store."""
    print(f"\n--- Ingesting into: {persist_path} (use_local={use_local}) ---")
    
    gemini_key = os.getenv("GEMINI_API_KEY", "") if not use_local else ""
    embedding_model = EmbeddingModel(api_key=gemini_key)
    vector_store = VectorStore(persist_directory=persist_path, embedding_model=embedding_model)
    
    chunker = TextChunker(chunk_size=700, chunk_overlap=120)
    chunks = chunker.split_documents(documents)
    print(f"Split {len(documents)} documents into {len(chunks)} chunks.")
    
    # Add chunks in batches of 40 to avoid any API request size or memory bottlenecks
    batch_size = 40
    total_added = 0
    for i in range(0, len(chunks), batch_size):
        batch = chunks[i:i+batch_size]
        try:
            added = vector_store.add_documents(batch)
            total_added += added
            print(f"Embedded batch {i//batch_size + 1}/{(len(chunks)-1)//batch_size + 1} ({len(batch)} chunks, cumulative: {total_added})")
        except Exception as e:
            print(f"Error embedding batch {i}: {e}")
            
    total_chunks = vector_store.count_chunks()
    print(f"Total chunks now in collection '{vector_store.collection_name}': {total_chunks}")
    return vector_store

def test_queries(vector_store: VectorStore):
    """Test retrieval on sample questions to ensure high precision."""
    print("\n=======================================================")
    print("RUNNING VALIDATION SEARCHES ON THE KNOWLEDGE BASE")
    print("=======================================================")
    retriever = Retriever(vector_store=vector_store)
    
    sample_queries = [
        "What is the fee structure for B.Tech in MITS Gwalior?",
        "Who is the Chief Warden and what are the hostel mess charges?",
        "What are the eligibility criteria and documents required for admission?",
        "What are the specialized laboratories in the Department of Information Technology?",
        "How much consultancy revenue was generated by Civil Engineering in 2023-2024?",
        "Who is Dr. Sanjay Tiwari and what is his department?",
        "Name some prominent alumni of MITS Gwalior in NITI Aayog and TRAI."
    ]
    
    for q in sample_queries:
        print(f"\n[Query]: {q}")
        results = retriever.retrieve(query=q, top_k=2)
        if results:
            top = results[0]
            print(f"-> Top Source: {top.filename} (Score / Match)")
            snippet = top.content.replace('\n', ' ')[:180]
            print(f"-> Snippet: {snippet}...")
        else:
            print("-> No results found!")

def main():
    root_dir = backend_dir.parent
    data_dir = root_dir / "data"
    
    if not data_dir.exists():
        print(f"Error: data directory {data_dir} does not exist.")
        return
        
    docs = load_knowledge_base_documents(data_dir)
    if not docs:
        print("No documents loaded!")
        return

    # Ingest into both primary storage locations:
    # 1. Root vectorstore (used when running commands from root)
    # 2. backend/vectorstore (used when running uvicorn inside backend/)
    target_dirs = [
        str(backend_dir / "vectorstore"),
        str(root_dir / "vectorstore")
    ]
    
    for target in target_dirs:
        # A. Ingest with Local ONNX Embeddings (all-MiniLM-L6-v2)
        store_local = ingest_into_store(docs, target, use_local=True)
        
        # B. Ingest with Gemini Embeddings (if API key available)
        gemini_key = os.getenv("GEMINI_API_KEY", "")
        if gemini_key and gemini_key != "your_gemini_api_key_here":
            try:
                ingest_into_store(docs, target, use_local=False)
            except Exception as e:
                print(f"Notice: Gemini embedding ingestion skipped or hit error: {e}")

    # Validate retrieval on the local store
    test_queries(store_local)
    print("\nSUCCESS! Vector embeddings generated and local vector database is fully ready to answer user questions!")

if __name__ == "__main__":
    main()
